### PR TITLE
Fix Spellcheck Bug

### PR DESCRIPTION
**Pull request by mynameisfiber**
I was getting `byte` errors with `hunspell`... using `decode` and not string casting bytes solved the problems.  The bugs were:
1. The list of corrections were of the form `b'hello'` instead of `hello`
2. When selecting a correction, I would get a `TypeError` about implicit byte casting:

```
Traceback (most recent call last):
  File "/home/micha/install/scudcloud/scudcloud-1.1/lib/speller.py", line 84, in <lambda>
    action.triggered.connect(lambda:self.replaceWord(element, word))
  File "/home/micha/install/scudcloud/scudcloud-1.1/lib/speller.py", line 58, in replaceWord
    text = text[:self.startPos] + new + text[self.startPos+len(word):]
TypeError: Can't convert 'bytes' object to str implicitly
```

Should work now!

### CODE REVIEW

**Comment by raelgc** [comment]
Hi @mynameisfiber, thanks for the PR!

Which distro are you using?

I've tried this change in Ubuntu 14.04 and got this error while right-clicking a bad-spelled word:

```
Traceback (most recent call last):
  File "/opt/scudcloud/lib/wrapper.py", line 63, in contextMenuEvent
    self.window.speller.populateContextMenu(menu, element)
  File "/opt/scudcloud/lib/speller.py", line 83, in populateContextMenu
    action = QtGui.QAction(suggests[i].decode('utf8'), self)
AttributeError: 'str' object has no attribute 'decode'
```

**Comment by mynameisfiber** [comment]
I'm on debian stretch/sid and running with python 3.4.4 with hunspell 0.3.3 installed... maybe that's the discrepancy?

**Comment by raelgc** [comment]
On Ubuntu, python version is Python 3.4.3.

According [this StackOverflow question](http://stackoverflow.com/questions/28583565/str-object-has-no-attribute-decode-python-3-error), all strings on Python3 are unicode strings.

Maybe we should check if `new` is byte, then decode only in this case.

**Comment by mynameisfiber** [comment]
@raelgc what version of `hunspell` do you have installed? It may be that i have a newer version that responds with bytes?

**Comment by raelgc** [comment]
I don't have `hunspell` itself installed, but version in Ubuntu 14.04 is `1.3.2-6`.

I have `hunspell-en-us` in version `20070829-4` and `python-hunspell` in  `0.1-1build2`.

hunspell

**Comment by raelgc** [comment]
Maybe we can use a `if` like this to test the string and solve both cases:

```
if str(type(new)) == "<class 'bytes'>":
    new = new.decode('utf8')
```

**Comment by mynameisfiber** [comment]
@raelgc So the problem is that I have the most recent version of hunspell (v0.3.3).  The hot fix is to do something like what you suggest:

```
if isinstanceof(new, bytes):
    new = new.decode('utf8')
```

However, #329 can also solve this by having the python `hunspell` module requirement be taken care of by pipy.  We'd just have to add a `requirements.txt` file added and have it linked in properly in `setup.py`.

**Comment by raelgc** [comment]
Superseeded by #361 (I've created a new PR due conflicts with master).

**Pull request closed without merging**
