### PR TITLE
Activity notification needed for multiple instances

### PR DESCRIPTION
**Pull request by raelgc**
Hi there --

When I have two browser tabs open with different slack instances, each turns red if there are new messages to me in it. Even if I'm focused on one, I can easily see that there are notifications or unread messages in the other. When you using the same functionality in scudcloud, the instance list down the left side does not indicate which instances have unread messages or activity.

For instance, here's the difference between Slack and Scudcloud:
slack
scud

Notice how the Slack browser tabs give me an important piece of information that doesn't exist on Scudcloud. I'd love to have the unread indicators in Scudcloud that appear on the browser version.

Thank you!

### CODE REVIEW

**Comment by raelgc** [comment]
Hi @martinb3, thanks for reporting this!

Can you just tell me how many tabs do you have opened now? Man, your tab size is so small, I can imagine you have more than 30 tabs opened at least :D

I just tested in browser, and I can see the red mark is displayed when you got mentioned. 

My initial idea for that is to try display a red right border in the team you got mentioned.

**Comment by martinb3** [comment]
HI @raelgc -- Thank you for triaging this :)

The tabs are small because I have pinned them as 'app tabs' in Firefox:
https://support.mozilla.org/en-US/kb/pinned-tabs-keep-favorite-websites-open

A bright red border would be awesome! Thank you!

**Comment by raelgc** [comment]
@martinb3 Wow, this is a really useful feature! Thank you for sharing this!

**Comment by raelgc** [comment]
Deployed, please update and test :)

**Comment by martinb3** [comment]
It works! Thank you :)

**Pull request merged**
