### PR TITLE
[RFC] Reorganize scudcloud to be more like a proper python package

### PR DESCRIPTION
**Pull request by stieg**
**Request for Comments.  Not Ready for Merging**

I'm putting this out there to get feedback on the patch.  Mainly these two patches reorganize the project to be more inline with a standard Python module would look like.  Everything relevant to the execution of the app is contained within the `scudcloud` directory.  This patch also contains a new setup.py file.

With this RFC I'm looking for commentary on where you think files should or should not go or what should be fixed or generally for comments or questions like "why did you do X?"  This patch series is intended to solve issue #85 when ready.  I know its a big change.

I still need to put the final touches on the setup.py file.  Then once that is working I can open a new PR for supporting an RPM spec file for Fedora.

LMK your thoughts.  Cheers.

### CODE REVIEW

**Comment by raelgc** [comment]
Great job, @stieg!

Just few questions:
1. Why `leftpane-src.js` was removed?
2. I really have no idea about this: to be a python package, is ScudCloud required to be installed in correct python packages folder? (In Ubuntu, I think it's `/usr/lib/python3/dist-packages/`)
3. A `__init__.py` is required? (No idea too, I just saw some python packages with it).

**Comment by stieg** [comment]
> Why leftpane-src.js was removed?

Didn't see any code using it.  So I removed it.  Did I miss something?  The leftpane.html and .css files are still under resources.

> I really have no idea about this: to be a python package, is ScudCloud required to be installed in correct python packages folder? (In Ubuntu, I think it's /usr/lib/python3/dist-packages/)

I believe so but am still figuring it out myself honestly.  First time doing this.

> A **init**.py is required? (No idea too, I just saw some python packages with it).

Yeah I see a warning for that too.  Will create one.

**Comment by raelgc** [comment]
`leftpane-src.js` is the source for `/opt/scudcloud/resources/leftpane.js`.

I never created a python package too. And well, this is my first python app and my first Qt app too (ScudCloud). So, I'm totally open for any suggestions.

**Comment by stieg** [comment]
> `leftpane-src.js` is the source for `/opt/scudcloud/resources/leftpane.js`.

Figured.  Is it needed?  Normally I prune out files that are not used by the app in one way or another.  I can add it back if you prefer, but don't see reason.  Open to suggestion here.

> So, I'm totally open for any suggestions.

I guess its the blind leading the blind eh?  Thanks for the feedback so far.  Sounds like you are open to the change, just got to complete it now.  All that remains is to update the current DEB and RPM files to still package the old way until I figure out how to get these files to best use setup.py for these processes.  Getting the .deb and .rpm files to build from `setup.py` will come in later PRs.  Then inclusion in mainline distros.  W00t.

**Comment by stieg** [comment]
Any further comments?  If no, go ahead and close the request.

**Comment by raelgc** [comment]
But we need that file for the project. We have 2 JS files, `scudcloud.js` and `leftpane.js`, both minified from the `-src` file. Why will we remove them from the repo? You just do not include them in the package.

**Comment by stieg** [comment]
Ah... Didn't understand that part.  Will restore it.

On Wed, Dec 16, 2015 at 12:29 PM, Rael Gugelmin Cunha <
notifications@github.com> wrote:

> But we need that file for the project. We have 2 JS files, scudcloud.js
> and leftpane.js, both minified from the -src file. Why will we remove
> them from the repo? You just remove them from the package.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/raelgc/scudcloud/pull/323#issuecomment-165201661.

## 

Andrew AV. Stiegmann

**Comment by raelgc** [comment]
I just got thinking... maybe we should have folders for the program itself (probably still `scudcloud1-1`), and then separate folders for system packages.

So, `debian` will be moved to root. The `.spec` file will require a `rpm` folder in root.

The `setup.py` will remain inside `scudcloud1-1`, as it'll part of the program.

The `-src.js` files probably we'll need to go to root too.

How about it?

**Comment by stieg** [comment]
> I just got thinking... maybe we should have folders for the program itself (probably still scudcloud1-1), and then separate folders for system packages.

The program itself _is_ in its own file named scudcloud.  I dropped the version suffix because it makes packaging unnecessarily harder when a major or minor version is upgraded and is frankly unnecessary since maintaining versions files and dirs is Gits job.  I strongly suggest it stay this way.

> So, debian will be moved to root. The .spec file will require a rpm folder in root.

:+1:   Happy to create separate dirs for deb and rpm files.

> The setup.py will remain inside scudcloud1-1, as it'll part of the program.

No can do.  Needs to be at the root of the project.  Plus its not part of the program.  Its just how the program gets installed the python way.

> The -src.js files probably we'll need to go to root too.

I'll create a directory called `src` and throw this file in there.  Work?

**Comment by raelgc** [comment]
For packaging, at least on Debian, it's easier have a folder with program name and major version.

But if not the case for RPM and others, at least we need a folder called `scudcloud` with the program. To keep program separate of repo files.

This is a best practice. Even for python packages. Example: https://github.com/mariano/snakefire/

So, I agree to keep `setup.py` in root, but have separate folders for program itself, DEB package and RPM package.

**Comment by stieg** [comment]
> For packaging, at least on Debian, it's easier have a folder with program name and major version.

Never heard this before?  Got any reading you can point me to?  Would like to understand why.

> But if not the case for RPM and others, at least we need a folder called scudcloud with the program. To keep program separate of repo files.
> 
> This is a best practice. Even for python packages. Example: https://github.com/mariano/snakefire/

Agree.  That is the way its structured in this RFC.  All files needed for execution of scudcloud are in the `scudcloud` directory.  Perhaps it would be easier if you cloned my repo and git reset hard to this branch.  It would be easier to see the file structure that way.

**Comment by raelgc** [comment]
From `dch` [manpage](http://manpages.ubuntu.com/manpages/precise/en/man1/dch.1.html):

> If the directory name of the source tree has the form  package-version,
> then debchange will also attempt to rename it if the (upstream) version
> number changes.  This can be prevented by using the --preserve  command
> line or configuration file option as described below.

While it's easier, it's not mandatory. We can pass version and package name by parameter, using `-v` for version and `--package` for package name and pass the `--preserve` to `dch` not change the folder name.

So, appears that we have a consensus here.

But, I still cannot see a folder for the program in the PR. I'm tracking the changes watching the [PR Files](https://github.com/raelgc/scudcloud/pull/323/files) and there I cannot see a folder for the program name (all ScudCloud files got moved to root).

And, off-topic: I can see you have a Snakefire fork too :)

**Comment by stieg** [comment]
> While it's easier, it's not mandatory. We can pass version and package name by parameter, using -v for version and --package for package name and pass the --preserve to dch not change the folder name.

Sounds like a plan to me.

> But, I still cannot see a folder for the program in the PR. I'm tracking the changes watching the PR Files and there I cannot see a folder for the program name (all ScudCloud files got moved to root).

I must be seeing it differently.  Here is one example:

`scudcloud-1.1/lib/resources.py → scudcloud/resources.py`

In my changes I got rid of the `lib` dir and moved its resources into the scudcloud directory.  This is correct because it a resource used only by the scudcloud app.

If everything had been moved to root then the above would look like this:

`scudcloud-1.1/lib/resources.py → resources.py`

Or perhaps we are talking about different things.

> And, off-topic: I can see you have a Snakefire fork too :)

Yep.  Back at my old company we were using campfire for a while before it was deprecated.  Was gonna do some work on it but obviously that didn't happen :P

**Comment by raelgc** [comment]
@stieg Indeed, most of program content is under `scudcloud` folder, my bad (I just saw the first changes, like the `.desktop` file and didn't pay attention to others).

Right, so we're close to finish this.

Nice you moved the main program to `__main__.py`!

So, please:
1. restore the LICENSE file;
2. restore `leftpane-src.js` moving to root;
3. create a `rpm` folder and move the `spec` file to it.

And what do you think about create a `/desktop` folder, to store `systray` images and the `.desktop` file? Or all to `resources`?

**Comment by stieg** [comment]
Ok... That should about do it.  Still need to fix up the installers but setup.py appears to be in great shape.  Take a look and LMK if there is anything else.  Otherwise I'll close this, finish up the packaging shifts and open a new PR

**Comment by raelgc** [comment]
LGTM! Go ahead!

**Comment by raelgc** [comment]
Just missing the LICENSE back!

**Comment by stieg** [comment]
> Just missing the LICENSE back!

I did restore the version of the LICENSE file at the top level of the projetct.  There were two LICENSE files.  Do you want both of them?  I don't see a need for that.  LMK.

**Comment by raelgc** [comment]
@stieg Just one is fine. Previously there were 2 to be listed in root project (for GitHub), and other to be included in Debian package. But as now we're moving stuff to root folder, you're right, one is enough.

Before I forget: I really appreciate you've included you as the python package maintainer! Thank for your efforts and initiative!

**Comment by immerrr** [comment]
There might be some inspiration to be borrowed from `gnome-terminator` which is a quite mature python package providing a gui application. The repo is here: http://bazaar.launchpad.net/~gnome-terminator/terminator/trunk/files.

**Comment by raelgc** [comment]
Thank you for the nice tip, @immerrr!

I can see its using `data` for images and desktop files that will be installed by package.

`debian` for the `.deb` stuff

Some nice tests too!

**Pull request closed without merging**
