### PR TITLE
Now build for CentOS, Red Hat Enterprise Linux, openSUSE, SUSE Linux …

### PR DESCRIPTION
**Pull request by mbajor**
…Enterprise Server and others is possible

### CODE REVIEW

**Comment by moonwolf-github** [comment]
Looks OK - i've replaced spec file on my opensuse build service and it works for F21 and F22. I can't check it for other distros (apart of CentOS) though.

**Comment by moonwolf-github** [comment]
I'm not sure about CentOS/RHEL - where will you get Qt4 and python3 from? I don't know about other distros.

**Comment by mbajor** [comment]
@moonwolf-github Here is build result for other distros.
https://build.opensuse.org/package/show/home:marcinbajor:scudcloud/scudcloud
You can add new repositories to your project and update README.md or we can switch to my project

> where will you get Qt4 and python3 from

Open Build Service resolves dependencies automatically

**Comment by moonwolf-github** [comment]
@mbajor yes, they build OK. But i didin't find python3 for CentOS6 i386 (it's in SCL only for x86_64). Same is for Qt4 bindings for python3 (CentOS6 and CentOS7). We shouldn't provide packages that are uninstalable.

**Comment by mbajor** [comment]
@moonwolf-github You have right. I've removed wrong repositories from my project. It looks that we can provide packages only for Fedora and openSUSE.

**Comment by moonwolf-github** [comment]
@mbajor i'll try as time permits to build necessary packages. So, i'll enable openSUSE repos and maybe you will update README.md accordingly?

**Comment by raelgc** [comment]
@moonwolf-github, can I merge this? Or CentOS and RHEL will be removed?

**Comment by moonwolf-github** [comment]
@raelgc no need to alter anything - we just won't build packages for these distros for now. So, you may merge (README should reflect SuSE though and maybe we should remove Fedora version number from it - @mbajor will you take care of it?)

**Comment by moonwolf-github** [comment]
I think it should be enough.

**Pull request merged**
