### PR TITLE
PEP8 format

### PR DESCRIPTION
**Pull request by aikikode**
- Reformat code according to [PEP8](https://www.python.org/dev/peps/pep-0008/) standard where possible
- Make tray icon always visible (which is expected behavior for any app)

### CODE REVIEW

**Comment by raelgc** [comment]
Hi @aikikode and thanks for all the changes!

The code is much better (sorry for my non python standard code)!

The only minor stuff: I really like don't have an icon in my systray for a lot of apps. Can you keep it optional?

**Comment by aikikode** [comment]
Hi @raelgc,
thanks for taking my patch into account!

Sure, I'll update the code. I have the following proposal then:
1) when user ticks 'Close to tray', tray icon should not appear. It should appear is the systray only when the main window is closed.
2) I'll add one more option e.g. 'Show tray icon' to make it permanently visible.

What do you think?

**Comment by moonwolf-github** [comment]
I would prefer see icon all the time (to bring window to the front for example). Second option will be better i think.

**Comment by moonwolf-github** [comment]
Note - bringing window doesn't work now, but at least desktops are switching when i click (and then window appears on the top of others). It may be windowmanager dependant.

**Comment by aikikode** [comment]
@moonwolf-github I meant to do both options. Although your proposal makes sense: rename 'close to tray' option to 'show tray icon'. From usability principles this solution is much better. Close the window -> close the program, not hide it in tray.

**Comment by moonwolf-github** [comment]
Well, i don't know. I like possibility to close window to hide it in tray...

**Comment by aikikode** [comment]
I'll add 'Show tray icon' option then.

**Comment by bkconrad** [comment]
Tested, works great. Tray icon option is a nice add. Needless to say the code looks a lot better too. Please merge.

:+1:

**Comment by aikikode** [comment]
Due the new version release this pull request has conflicts. I opened https://github.com/raelgc/scudcloud/pull/189 with updated code that can be merged without any conflicts.

**Pull request closed without merging**
