### PR TITLE
Enable handling of files URLs

### LINKED ISSUE #74: Open posts & files within Scudcloud
It would be great to have the ability to edit posts within Scudcloud and not be forced into an external browser for the following URL locations:

`https://FOO.slack.com/files/`
`https://FOO.slack.com/files/USER/POST_ID/POST_NAME/edit`

Is this possible?

(BTW, super fantastic app!! :+1: :heart: )

### PR DESCRIPTION
**Pull request by ghost**
@raelgc I think this might fix #74 

Please have a look to see if this commit makes sense. I'm just piggy-backing on @immerrr's good code.

### CODE REVIEW

**Comment by raelgc** [comment]
Hi @xHN35RQ, thanks for sending this. But files are not supposed to be opened by `xdg-open`?

**Comment by ghost** [comment]
Ok right now for me if I upload a PDF and then click on either the download link or the page link, it opens in Browser and tries to download. However I have a PDF Reader set system-wide so for some reason Scudcloud is not sending the PDF to the Reader but instead to the Browser.

**Comment by michaelherold** [comment]
`xdg-open` can be used to open any file belonging to a MIME type that you have a preferred application set for. Also, if you're using a desktop environment `xdg-open` merely delegates to the environment's file opener (i.e. `gvfs-open` for Gnome, `kde-open` for KDE, etc.)

Since you're primarily targeting Ubuntu, I'd say it's probably safe to delegate everything to `xdg-open`. Totally up to you though.

**Comment by ghost** [comment]
So what is the status on this? As it is right now, Scudcloud does not honor xdg-open but instead pushes all `file` links (pdf) to the default web browser. If I click "Download"on a PDF file within Scudcloud, the link is sent over to web browser instead of downloading the PDF directly... or displaying the PDF within Scudcloud.

**Pull request closed without merging**
