### PR TITLE
Notification tray icon

### PR DESCRIPTION
**Pull request by raelgc**
Would love to have a notification tray icon. I find it always helps when there is unread notifications for a messaging app to have an icon that changes if there are unread messages.

Thanks for ScudCloud!

### CODE REVIEW

**Comment by raelgc** [comment]
@collinpeters I've published a first attempt to an icon on systray/notification area.

Can you, please, test it?

You need first to run a `sudo apt-get update && sudo apt-get upgrade`.

Then, after close/reopen ScudCloud, enable the option in `File` > `Systray Icon`.

**Comment by collinpeters** [comment]
Cool stuff @raelgc. After installation and restart I enabled the systray icon. Right now it is showing up as a question mark with two options: show and exit. What kind of features have you implemented so far?

**Comment by raelgc** [comment]
Question mark? This is bad. Should be the ScudCloud monochromatic icon when "normal" and a blue icon when new messages arrive.

Probably I need to add more resolutions of the .svg notification icon file.

**Comment by raelgc** [comment]
@collinpeters Can you, please, test this for me to see if the icon will be now properly displayed?

First: close ScudCloud.

Then run the 3 following commands:

```
sudo mv /usr/share/icons/ubuntu-mono-light/apps/22/scudcloud* /usr/share/icons/ubuntu-mono-light/scalable/apps/
sudo mv /usr/share/icons/ubuntu-mono-dark/apps/22/scudcloud* /usr/share/icons/ubuntu-mono-dark/scalable/apps/
sudo xdg-icon-resource forceupdate
```

Then open ScudCloud again and check if the icon is now the correct one.

**Comment by collinpeters** [comment]
That didn't seem to help. When I launch ScudCloud from a terminal I see the following in the output
`QSystemTrayIcon::setVisible: No Icon set`

I also see that when I toggle the option in the menu.

**Comment by raelgc** [comment]
Right, thanks for checking that @collinpeters 
Now I'm just finishing my regular work and it's time to pick kids in school.
Later at my night I'll solve this.
Sorry for the inconvenience!

**Comment by collinpeters** [comment]
No inconvenience at all! I'm super happy with ScudCloud and the quick response!

**Comment by raelgc** [comment]
@collinpeters Can you try this, please?

```
sudo cp /usr/share/icons/ubuntu-mono-dark/scalable/apps/scudcloud* /usr/share/icons/hicolor/scalable/apps/
sudo xdg-icon-resource forceupdate
```

Close and restart ScudCloud.

**Comment by collinpeters** [comment]
Cool! That got me the regular icon for sure. Not sure about the attention icon yet. I tried some webhooks to a private group with an @ mention on myself but the icon didn't change. Will see once I get a regular message from someone.

**Comment by collinpeters** [comment]
Cool! It does work with a regular message! I'm really not sure why the webhook method didn't work. How is the icon colour change hooked up? i.e. through a direct message only? based on slack prefs?

**Comment by raelgc** [comment]
I've tried to follow the wobbling + `unread messages count` behaviour: only when you got mentioned. 

This is the only situation where Slack displays number of unread messages in the left pane. So I tried to follow that.

**Pull request merged**
