### PR TITLE
How do I enable desktop notifications?

### PR DESCRIPTION
**Pull request by raelgc**
Every time I load ScudCloud, it (or rather Slack) asks me to enable desktop notifications. If I attempt to do that in the preferences, it says “your browser should now be presenting you with the option…”, but there's no permission request, and if I close and reopen preferences, notifications are still not enabled.

### CODE REVIEW

**Comment by lalomartins** [comment]
@raelgc it just asked me for permission again, and it wasn't even started recently. I think it might have been on return from suspend?

**Comment by raelgc** [comment]
@lalomartins For sure it's related to some sleep/wakeup situation, but I'm still not able to reproduce it in a consistent way to try a fix. Let me know if you find an always reproducible scenario.

**Comment by raelgc** [comment]
I'm publishing a new possible fix for notifications when Slack is trying to reconnect.

**Comment by lalomartins** [comment]
@raelgc of course that's not a definite negative, but it survived the last 2 suspends without asking for permission again (that running the .deb from about 6h after your last post). :+1:

**Comment by lalomartins** [comment]
bad news, sorry — just failed again :crying_cat_face: 

maybe faster JS isn't the answer? Is it possible to detect a wakeup and reload everything? Because maybe Slack itself is doing something like that, but it's reloading imperfectly (or maybe overwriting your JS patches when it reloads).

**Comment by raelgc** [comment]
@lalomartins Don't worry, let's hunt and kill this bug! :D 

Do you remember in which situation notifications stopped to work? If after a resume, or after desktop login, etc?

**Comment by lalomartins** [comment]
after a resume, sorry forgot to state that, since it's the last thing we were discussing :smile_cat:

**Comment by lalomartins** [comment]
I don't know why this resume made it fail and the other two I posted about didn't. Maybe it stayed suspended longer? But my best theory is that Slack updated their code while I was on suspend, which I'm pretty sure would trigger a reload. In fact, now that I've written that, I'm suspecting that could cause a fail even without a suspend, although that would require quite a bit of luck to test…

**Comment by raelgc** [comment]
I saw today too one situation where the notifications just stopped to appear (while the yellow banner at the top asking to active them was not displayed). But I was unlucky to reproduce it too. Maybe, like you said, they force some update in some situations.

**Comment by lalomartins** [comment]
Yes, the reason I came up with that hypothesis is that I know for a fact they pushed an update today

**Comment by raelgc** [comment]
I'm glad you mentioned it, I was not even aware of it :)

**Comment by lalomartins** [comment]
Will webkit tell you when the page is reloaded or unloaded? I have a hunch this just might be it.

**Comment by raelgc** [comment]
There are events for `startLoading` and `stopLoading`, but sometimes appears like Slack changes the URL without fire them.

One possible solution will be override Slack reload method (there is an internal one) to add a cookie when reload is fired, then if cookie is present when page is loaded, we try to inject the desktop notification again.

Other issue I see here sometimes: the `notify-osd` daemon goes crazy and all notifications stop to work. Then if I restart it, some programs will notify again, but others (like ScudCloud) only after a program restart.

**Comment by lalomartins** [comment]
So Slack had an update today and my ScudCloud didn't break.

**Comment by lalomartins** [comment]
… then I had to re-login after enabling 2fa, and that did break it :-D

**Comment by raelgc** [comment]
cool... probably it's something really related to some restart of `notify-osd`. I can reproduce that killing `notify-osd` and restarting it.

Probably I'll try some code to catch that during the weekend :)

**Comment by lalomartins** [comment]
logging out and back in to Slack wouldn't restart notify-osd, would it?

**Comment by raelgc** [comment]
You enabled 2fa in Slack?

**Comment by lalomartins** [comment]
right. They just released in today's update and I'm a big fan of 2fa.

**Comment by raelgc** [comment]
@lalomartins I think with fix #93 notifications will not stay even after a notify-osd crash :D

**Comment by lalomartins** [comment]
oho. I've been ignoring Update Manager because I want to dist-upgrade to 15.04 when I'm done with my current project :smiley_cat: but I'll accept the ScudCloud update next time and let you know how it goes for me.

**Comment by lalomartins** [comment]
Ok, fix confirmed. I suspended, came back, no crash reports, no banners requesting I enable notifications, and notifications actually still work. :+1:

**Pull request merged**
