### PR TITLE
Add qtwebkit dependency, drop xdg-icon-resource action from postinst

### PR DESCRIPTION
**Pull request by immerrr**
- ~~`xdg-utils` is required for `xdg-icon-resource` used in `postinst`~~
- `libqtwebkit4` dependency will make it impossible to run into a "hung at login" issue on Precise

I'd also recommend `wrap-and-sort` script for uniformity of dependency lists, but that's matter of preference and I can rollback that commit if you like.

### CODE REVIEW

**Comment by raelgc** [comment]
Hi @immerrr,

Thanks for the changes, I love them all!

Just one: `xdg-utils` is not a real requirement, it's automatically called by `dpkg` just to update the `.desktop` files and icons cache. If it's not present, we can just ignore it.

Can you just remove this one, please?

**Comment by immerrr** [comment]
We couldn't leave it as is because failing command in postinst script leaves package in half-configured state (because of `set -e` in the beginning):

``` term
$ sudo apt-get -y install scudcloud
Reading package lists... Done
Building dependency tree       
Reading state information... Done
scudcloud is already the newest version.
0 upgraded, 0 newly installed, 0 to remove and 156 not upgraded.
1 not fully installed or removed.
After this operation, 0 B of additional disk space will be used.
Setting up scudcloud (1.0-17) ...
/var/lib/dpkg/info/scudcloud.postinst: 23: /var/lib/dpkg/info/scudcloud.postinst: xdg-icon-resource: not found
dpkg: error processing scudcloud (--configure):
 subprocess installed post-installation script returned error exit status 127
Errors were encountered while processing:
 scudcloud
E: Sub-process /usr/bin/dpkg returned an error code (1)
vagrant@precise64:~$ dpkg -s scudcloud | grep Status
Status: install ok half-configured
```

However xdg-icon-resource command can be dropped altogether, because it only updates the cache of `hicolor` icon theme and that is already handled by a trigger in hicolor-icon-theme package. Other icon themes are updated by dh_icons debhelper script (and that also happens automatically).

**Comment by raelgc** [comment]
Right, and additionally I just remembered we're using `xdg-open` to handle external links.

Just one last question: why did you remove `xdg-icon-resource forceupdate` from `postinst`?

**Comment by immerrr** [comment]
I've summarized it shortly above :)

A longer explanation is that `#DEBHELPER#` in `postinst` expands into

``` bash
# dh_installdeb will replace this with shell code automatically
# generated by other debhelper scripts.

# Automatically added by dh_icons
if which update-icon-caches >/dev/null 2>&1 ; then
    update-icon-caches /usr/share/icons/ubuntu-mono-light /usr/share/icons/ubuntu-mono-dark
fi
# End automatically added section
```

`dh_icons` does that for all icon-related directories it finds created when the package is built.  It does not do that for `hicolor` theme, because `hicolor-icon-theme` installs a trigger [which does the same automatically](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=521181).

**Comment by immerrr** [comment]
I have myself forgotten about `xdg-open` and dropped the dependency, I'll put it back.

**Comment by raelgc** [comment]
@immerrr Sorry for ask so many questions and thank you for your patience to answer all :)

**Comment by raelgc** [comment]
So, now without `xdg-utils` running in `postinst`, can we drop this dependency?

**Comment by immerrr** [comment]
We could drop it if we were not using `xdg-open`.

**Comment by raelgc** [comment]
So, basically, is everything fine now, right?

**Comment by immerrr** [comment]
I think so.

There's a lot of good debhelper scripts can do for packages automatically, including support for multiple versions of python, compiling python sources and cleaning compiled files afterwards (as of now, the package leaves `__pycache__` directory in its wake after deletion). I'll post this as a separate issue.

**Comment by raelgc** [comment]
@immerrr Yeap, I read something about it (that I should create a python package first, etc, etc). About the deletion, if we'd not about create a proper python package, we should add a `postrm` script to delete the `__pycache__`.

I just have not enough time for now to proper learn about python packages (consider that I just learn the basics of python to build this package), and in my spare time, and to help others.

I.e., I really appreciate all your help. This is really immeasurable and make me motivated to continue :)

**Pull request merged**
