### PR TITLE
Allow zooming in to reduce eye strain on high-dpi displays

### PR DESCRIPTION
**Pull request by raelgc**
I have a 1080p laptop display and use 120-140% font size everywhere but scudcloud doesn't support zoom shortcuts and the text feels too small to read.

### CODE REVIEW

**Comment by raelgc** [comment]
@immerrr Is shortcuts to Zoom enough?

**Comment by immerrr** [comment]
Yup, should be..

**Comment by raelgc** [comment]
I mean, they works, but just wondering if you want something more advanced, like save latest zoom state, etc.

**Comment by immerrr** [comment]
It would be nice to preserve zoom across sessions. For now it is ok as it is only a couple keypresses away.

**Comment by raelgc** [comment]
Done with saving/restoring :)

Probably tomorrow morning I'll publish the updated version with all latest fixes/improvements.

**Pull request merged**
