### PR TITLE
Doesn't support uploading images from Clipboard

### PR DESCRIPTION
**Pull request by raelgc**
What would it take to support pasting an image into ScudCloud? 

Current Slack behavior automatically uploads and publishes images from the Clipboard when pasted into the Slack window.

### CODE REVIEW

**Comment by raelgc** [comment]
@KyleMacey I just published a new version. Can you run a `sudo apt-get update && sudo apt-get upgrade` and tell me if it works in your side?

**Comment by kylemacey** [comment]
Cool, so it works now, but it only does the "skip dialog" upload, which you usually only get when you hold <kbd>shift</kbd> when dropping in Chrome.

Also, it opens the "Create Snippet" dialog at the same time that the file is uploaded.

**Comment by kylemacey** [comment]
Well, wait. I just tried to reproduce to get a screen shot and it seems to be working fine now.

**Comment by kylemacey** [comment]
Thanks a lot! Works like a dream.

**Pull request merged**
