### PR TITLE
Add version option command line (#186)

### PR DESCRIPTION
**Pull request by alexander-jiang**
Addresses #186.

Uses [subprocess.check_output](https://docs.python.org/2/library/subprocess.html#subprocess.check_output) to print the output of `$ rpm -q scudcloud`

### CODE REVIEW

**Comment by alexander-jiang** [comment]
@raelgc Just pinging you about this PR. Let me know if there's other implementation methods that you'd prefer.

**Comment by raelgc** [comment]
@alexander-jiang I really like your solution!

But we have a small problem with it... actually ScudCloud runs in several distros, some of them not even using a package manager.

So, we should create a constant with the version in the `scudcloud-1.0/scudcloud` file, and `-v` or `--version` printing it, to not rely in any package manager.

**Comment by alexander-jiang** [comment]
@raelgc Just made a commit. I was thinking of implementing it this way (i.e. storing the version number as a constant) at first, but I thought it would be better if the solution used something that would work for those with old versions (which would only have their version numbers accessible through a package manager).

**Comment by raelgc** [comment]
@alexander-jiang I used your code, just a bit modified. Thanks!

**Pull request closed without merging**
