### PR TITLE
Update document about how to install scudcloud on 12.04 to use ppa of gstramer

### PR DESCRIPTION
**Pull request by garaemon**
libqtwebki4 requires libgstreamer-plugins-base1.0-0 but 12.04 provides
libgstreamer-plugins-base0.10-0. In order to install libqtwebki4,
need to update gstreamer 1.0

```
$ sudo apt-get install libqtwebkit4
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 libqtwebkit4 : Depends: libgstreamer-plugins-base1.0-0 (>= 1.0.0) but it is not
 installable
E: Unable to correct problems, you have held broken packages.
```

### CODE REVIEW

**Comment by raelgc** [comment]
@garaemon If I correctly remember, all the `gstreamer` files are already included in the 12.04 Backport PPA. 

Can you confirm this, @immerrr?

**Comment by immerrr** [comment]
@raelgc yes, i have missed one of the dependencies and the plugins package was never built.  I have copied the dependency and launchpad should eventually publish them all.

**Comment by raelgc** [comment]
@immerrr just let me know if everything got published, so we can close this PR or merge it.

**Comment by immerrr** [comment]
should be ok now

**Comment by raelgc** [comment]
@garaemon I'll close this PR, as @immerrr fixed the issue. 

If you can test this, that would be great.

**Comment by garaemon** [comment]
I confirmed that ppa fixed the issue now.

```
$ sudo apt-get install scudcloud
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following package was automatically installed and is no longer required:
  foreman
Use 'apt-get autoremove' to remove them.
The following extra packages will be installed:
  fonts-lato libgstreamer-plugins-base1.0-0 libgstreamer1.0-0 liborc-0.4-0 libqtwebkit-dev
  libqtwebkit-qupzillaplugins libqtwebkit4 python3 python3-dbus python3-gi python3-minimal python3-pyqt4
  python3-sip
Suggested packages:
  gstreamer1.0-tools gstreamer1.0-plugins-base python3-doc python3-tk python-dbus-doc python3-dbus-dbg
  python3-pyqt4-dbg
The following NEW packages will be installed:
  fonts-lato libgstreamer-plugins-base1.0-0 libgstreamer1.0-0 libqtwebkit-qupzillaplugins python3 python3-dbus
  python3-gi python3-minimal python3-pyqt4 python3-sip scudcloud
The following packages will be upgraded:
  liborc-0.4-0 libqtwebkit-dev libqtwebkit4
3 upgraded, 11 newly installed, 0 to remove and 97 not upgraded.
Need to get 17.6 MB of archives.
After this operation, 38.0 MB of additional disk space will be used.
Do you want to continue [Y/n]? y
Get:1 http://jp.archive.ubuntu.com/ubuntu/ precise-updates/main python3-minimal amd64 3.2.3-0ubuntu1.2 [12.0 kB]
Get:2 http://jp.archive.ubuntu.com/ubuntu/ precise-updates/main python3 amd64 3.2.3-0ubuntu1.2 [30.6 kB]
Get:3 http://jp.archive.ubuntu.com/ubuntu/ precise/main python3-dbus amd64 1.0.0-1ubuntu1 [101 kB]
Get:4 http://ppa.launchpad.net/rael-gc/scudcloud/ubuntu/ precise/main fonts-lato all 2.0-1 [2,701 kB]
Get:5 http://jp.archive.ubuntu.com/ubuntu/ precise-updates/main python3-gi amd64 3.2.2-1~precise [194 kB]
Get:6 http://jp.archive.ubuntu.com/ubuntu/ precise/main python3-sip amd64 4.13.2-1 [72.9 kB]
Get:7 http://jp.archive.ubuntu.com/ubuntu/ precise/main python3-pyqt4 amd64 4.9.1-2ubuntu1 [3,113 kB]
Get:8 http://ppa.launchpad.net/immerrr-k/qtwebkit4-backport/ubuntu/ precise/main libgstreamer1.0-0 amd64 1.2.1-1~ubuntu12.04.1~gstdev1 [1,905 kB]
Get:9 http://ppa.launchpad.net/immerrr-k/qtwebkit4-backport/ubuntu/ precise/main liborc-0.4-0 amd64 1:0.4.18-1~ubuntu12.04.1~gstdev1 [190 kB]
Get:10 http://ppa.launchpad.net/immerrr-k/qtwebkit4-backport/ubuntu/ precise/main libgstreamer-plugins-base1.0-0 amd64 1.2.1-2ubuntu1~ubuntu12.04.1~gstdev1 [682 kB]
Get:11 http://ppa.launchpad.net/immerrr-k/qtwebkit4-backport/ubuntu/ precise/main libqtwebkit-dev amd64 2.3.2-0ubuntu7~precise1~ppa1 [75.6 kB]
Get:12 http://ppa.launchpad.net/immerrr-k/qtwebkit4-backport/ubuntu/ precise/main libqtwebkit4 amd64 2.3.2-0ubuntu7~precise1~ppa1 [8,491 kB]
...
```

**Comment by raelgc** [comment]
Excellent! 

Good job, guys! Thank you @garaemon for raising and testing this issue and thank you @immerrr for fixing it!

**Pull request closed without merging**
