### PR TITLE
Close to Tray

### PR DESCRIPTION
**Pull request by raelgc**

### CODE REVIEW

**Comment by collinpeters** [comment]
After I close to tray, then I am able to launch a second instance of ScudCloud if launched from the panel. Also it seems the panel notifications stop working?

**Comment by raelgc** [comment]
@collinpeters You can launch a second instance of ScudCloud even if it's not closed to tray. About the notifications not working, I'll need to investigate.

**Comment by collinpeters** [comment]
Would be nice to have an option to not allow a second instance to be launched. I can see that for someone with multiple teams it might be a feature to have two instances.

To clarify, I'm not sure if it is notifications as whole, or just the launching wobbling.

**Comment by raelgc** [comment]
Indeed, I should prevent 2 windows, as they'll share the same config... the improvement #6 will fix the support for multiple teams.

**Pull request merged**
