### PR TITLE
Fedora package

### PR DESCRIPTION
**Pull request by moonwolf-github**
Spec file for generating RPM for Fedora (tested on F21). I also had to add trailing semicolon in .desktop file.

### CODE REVIEW

**Comment by raelgc** [comment]
Hi @moonwolf-github, loved this pull request!

Just a couple of questions: 

1 - Where the RPM will be located?
2 - Can you add instructions about how to install in README file?

**Comment by moonwolf-github** [comment]
Well - i didn't put RPM into public, i don't know where. I must look for some solution. Then i will update README.

**Comment by raelgc** [comment]
I see people using http://openbuildservice.org/ to host packages similar to Ubuntu PPAs.

**Comment by moonwolf-github** [comment]
Yes, but it looks like build system and you need to deploy it on some public server owned by you. I'm a little concerned doing so (i'm not a full-time administrator). I have to find host service for this (maybe EPEL repo will be interested in packaging scudcloud? I'll ask them).

**Comment by raelgc** [comment]
@moonwolf-github If I correctly understood, it's very similar to Launchpad: you need to upload the source, then openbuildservice.org will build it and distribute it.

If you can just check the commands to upload the source in there, I can do it every release.

**Comment by moonwolf-github** [comment]
Right, i missed it - looks like you are right. I'll try to manage it ASAP.

**Comment by moonwolf-github** [comment]
Just tested this on fresh F21 install - looks OK. But notice: i'm not very experienced in RPM builds so i can't promise that everything is fine with this package. Also i'm not native english speaker, so excuse me for any mistakes (:)

**Comment by moonwolf-github** [comment]
Another thing - this is package made from HEAD not tag.

**Comment by raelgc** [comment]
Thank you @moonwolf-github and sorry for my late on this.

**Comment by moonwolf-github** [comment]
Great! Maybe i'll try to create package for CentOS7 also? Will see...

**Pull request merged**
