### PR TITLE
Unity Required?

### PR DESCRIPTION
**Pull request by raelgc**
Hello! 

Disclaimer: I use Cinnamon.

``` bash
$ scudcloud
Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 2135, in _find_spec
AttributeError: 'DynamicImporter' object has no attribute 'find_spec'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/scudcloud", line 4, in <module>
    from scudcloud import ScudCloud
  File "./scudcloud.py", line 9, in <module>
  File "/usr/lib/python3/dist-packages/gi/importer.py", line 53, in find_module
    'introspection typelib not found' % namespace)
ImportError: cannot import name Unity, introspection typelib not found
```

Is Unity required?

Great looking app! Hopefully I can use it.

### CODE REVIEW

**Comment by raelgc** [comment]
Hi @kellevan, thanks for reporting this issue! 

Basically, in this first version, Unity was required (due wobbling, quicklist and libnotify). But I think it'll be not that hard to make it work in other DEs.

I'll make it.

**Comment by raelgc** [comment]
@kellevan I've just published a new version. 

Can you run a `sudo apt-get update && sudo apt-get upgrade` and check if ScudCloud is working fine on Cinnamon, please?

**Comment by goodroot** [comment]
@raelgc !

Beautiful work - picked up immediately.

Application is functional. 

I will let you know if any other oddities appear on Cinnamon, but seems great.

From a feature perspective, 'close to tray' would be the only thing that pops out.

Thank you! This definitely fixes an issue with using the browser to run slack -- notifications just... weren't right.

**Comment by raelgc** [comment]
@kellevan Maybe the `File` > `Systray Icon` should be `Minimize to Tray`. When `checked`, ScudCloud minimize will hide it to the tray icon.

**Comment by raelgc** [comment]
@kellevan `Close to Tray` is alive :)

**Comment by goodroot** [comment]
Rael!

Working perfectly.

You do wonderful work.

Thanks again!

**Pull request merged**
