### PR TITLE
fix dictionary path check

### PR DESCRIPTION
**Pull request by christofdamian**
`getDictionaryPath()` returns `''` when nothing is found and not `None`

### CODE REVIEW

**Comment by raelgc** [comment]
@christofdamian Thank you for pointing that! After your PR, I took a look in python documentation and saw that we can check using `not dictionaryPath` to check if string is not false (which includes `None` and ``).

So, can you update your PR to be like this?

``` python
if not dictionaryPath or not language:
```

What do you think?

**Comment by christofdamian** [comment]
Sounds good. I'll will update it tomorrow morning

**Comment by christofdamian** [comment]
updated now

**Comment by paoloantinori** [comment]
Hi guys, this bug totally prevents scudcloud to stat on Fedora 22 with 

```
rpm -qa | grep scudcloud
scudcloud-1.0.70-5.1.noarch

date
Tue 29 Sep 11:16:51 CEST 2015
```

**Comment by christofdamian** [comment]
@paoloantinori yes, that is how I discovered it :-)

**Comment by raelgc** [comment]
Thank you for all the work (discover and fix)!

**Pull request merged**
