### PR TITLE
Moving to a more pythonic model

### PR DESCRIPTION
**Pull request by stieg**
Ok... pretty close to ready.

This change has all of the migrations needed to make the project more like a proper python project.  It consolidates all of the scudcloud python modules into the scudcloud package, creates a **main**.py for module execution, creates a setup.py for standardized python installation, and does many small things like fixing up how version info is handled and migrating resources into logical directories.

What remains is some testing on the packaging systems that create the current packages.  I updated all the spec/deb files but have not tested them as of yet.

Any feedback you have is great.  Its ready for merge save the note about testing above.  Sorry for the massive size of the change.

### CODE REVIEW

**Comment by mynameisfiber** [comment]
I like the cleanup to the installation.  There's no reason not to submit this to pypi once this is merged to make installation as easy as `pip install scudcloud`

**Comment by raelgc** [comment]
Thank you @stieg!

Tomorrow I'll clone this in a local branch to test the package locally.

**Comment by raelgc** [comment]
I've checked out locally this PR and merged master. 
Still need to fix debian install file.
Pushed to branch [329](https://github.com/raelgc/scudcloud/tree/329-pythonic-model)

**Comment by raelgc** [comment]
For the setup process, I had to install `python3-setuptools` (`sudo apt-get install python3-setuptools`) on Ubuntu. Weird, I thought it was installed by default.

But, the setup process worked fine, and ScudCloud got installed! Nice work, @stieg!

Now I just need to update the Debian install. And bump version to `1.2` as this rework you've done is a huge step!

**Comment by stieg** [comment]
Glad its working.  Do note the change on the imports on scudcloud going forward.  You have to import names as if you are outside the module so

``` python
from resources import Resources
```

becomes

``` python
from scudcloud.resources import Resources
```

That may creep up on ya when you merge against later changes.  Thanks for your time in working with the deb files.

**Comment by raelgc** [comment]
One note: for some reason (maybe `setuptools`) package is installed under `/usr/local/lib/python3.4/dist-packages/`, while I have all other python3 packages installed at `/usr/lib/python3/dist-packages/`.

**Comment by stieg** [comment]
That is strange.  It installed to the correct location on Fedora 23 @raelgc.  What distro are you on?

**Comment by raelgc** [comment]
Ubuntu 14.04. And, while I have other python packages, `setuptools` was not installed. Wondering if they were installed by `distribute`.

**Comment by raelgc** [comment]
Or probably `distutils`, need to check.

**Comment by stieg** [comment]
Hey @raelgc anything I can help with here.  I just did complete and test the new fedora spec file (the main reason for doing the setup.py work) and its good so once this is committed I can move forward with getting this into Fedora.  LMK.

**Comment by drohm** [comment]
When this ticket is completed, will this change the way Scudcloud is installed?  Will the ppa be shutdown in favor of using pip for installation?

**Comment by stieg** [comment]
> When this ticket is completed, will this change the way Scudcloud is installed?

Effectively yes.

> Will the ppa be shutdown in favor of using pip for installation?

I doubt it.  @Raelgc is working on adapting these changes for the PPA froom what I understand.  The entire point of this change is to move to standard python installation model that large distros like Fedora prefer so that we can get this project mainlined in their repos.  I haven't mainlined anything in Debian ever, so perhaps that would be the next steps after Fedora.  Moving to this model certainly simplified the RPM spec file for Fedora.

**Comment by raelgc** [comment]
@stieg is right, it'll work both ways: directly from `setup.py` and from the PPA, like current days.

Sorry for my absence these days: heavy work + kids. I'll resume my work in this branch today!

**Comment by raelgc** [comment]
On Ubuntu, when `Close to Tray` is enabled, the notification area (aka systray) icon is broken. 

The themes got installed at `/usr/local/lib/python3.4/dist-packages/scudcloud-1.1.11-py3.4.egg/share/icons/`.

Can Qt find them in this place? Or should we put icons again at `/usr/share/icons/`?

**Comment by raelgc** [comment]
@stieg Probably I'll move the `debian` folder to root. This will make my life easier to build the package. If not, I'll need to run 2 additional steps for every new release.

# Caveats

Notes for myself about some caveats:
- I had to download `python3-stdeb` from `vivid (14.10)`, as this package do not exists in `trusty (14.04)`.
- I've used [`stdeb`](https://pypi.python.org/pypi/stdeb/0.8.5) to build a sample package with:
  
  ```
  python3 setup.py --command-packages=stdeb.command bdist_deb 
  ```

Then I've made several tweaks to use existing deb package following https://wiki.debian.org/Python/Packaging guide. Files got installed properly under `usr/lib/python3/dist-packages/`, and the icon in the notification area worked fine.

# Finally: what's missing
1. The icon used in the launcher is not the purple one, it's from the mini icons from the theme. Probably a simple tweak in the `desktop` file.
2. In Ubuntu, icons should be placed at `ubuntu-mono-dark` and `ubuntu-mono-light` to respect current theme. Probably a simple `.link` file in the package to create a symlink will solve this.

**Comment by raelgc** [comment]
@stieg Question: `setup.py` is mimicking a bit the old manual setup, moving icons to `mono-dark` and `mono-light` folders. Those folders exists in Fedora? 

Because in Ubuntu, they should be `ubuntu-mono-dark` and `ubuntu-mono-light`. Not sure if I missed this in the manual setup instructions.

**Comment by stieg** [comment]
> Sorry for my absence these days: heavy work + kids. I'll resume my work in this branch today!

I hear that.  Time is elusive.

> Probably I'll move the debian folder to root. This will make my life easier to build the package. If not, I'll need to run 2 additional steps for every new release.

Do it.

> Question: setup.py is mimicking a bit the old manual setup, moving icons to mono-dark and mono-light folders. Those folders exists in Fedora? 

Looking at my system it would appear not.  I was just using that as a template to work off of.  If its wrong, easy to fix.  If you need to alter the name in Ubuntu  modify the `_data_files` method in setup.py to special case the location for Ubuntu systems.

**Comment by raelgc** [comment]
All changes here (and more) are in PR #340.

**Pull request closed without merging**
