### PR TITLE
ImportError: bad magic number

### PR DESCRIPTION
**Pull request by raelgc**
Not able to run:

```
$ lsb_release -a
No LSB modules are available.
Distributor ID: LinuxMint
Description:    Linux Mint 16 Petra
Release:    16
Codename:   petra
$ scudcloud 
Traceback (most recent call last):
  File "/usr/bin/scudcloud", line 4, in <module>
    from scudcloud import ScudCloud
ImportError: bad magic number in 'scudcloud': b'\xee\x0c\r\n'
```

### CODE REVIEW

**Comment by raelgc** [comment]
Hi @giAtSDU, thank you for reporting this issue.

If I correctly remember, this issue is present when I try to run ScudCloud with python2 instead of python3.

Anyway, you're using Mint, right? This first version requires Unity, but I'll make it work with other DEs, like described in #12

**Comment by raelgc** [comment]
@giAtSDU I've just published a new version. 

Can you run a `sudo apt-get update && sudo apt-get upgrade` and check if ScudCloud is working fine on Cinnamon, please?

**Comment by giAtSDU** [comment]
@raelgc I am  getting the same error. 

```
#!/usr/bin/env python3
```

By the way, python 3 is specified in your runnable, so it must be something else (than python 2) causing the problem.

**Comment by giAtSDU** [comment]
@raelgc thanks for a quick attempt to solve the problem

**Comment by raelgc** [comment]
@giAtSDU, I've found the reason: I generate `.pyc` (compiled python) files, and maybe the python3 version is different in your system.

Can you run, in terminal, `python3 --version` and tell me the output?

To me:

``` term
$ python3 --version
Python 3.4.0
```

**Comment by giAtSDU** [comment]
```
$ python3 --version
Python 3.3.2+
```

**Comment by raelgc** [comment]
Thanks @giAtSDU, this explains the error.

I was about ask you to install a python PPA with newest version, but I think the easiest solution is just to include the plain `.py` (source) files and let the installed python take care of them.

**Comment by giAtSDU** [comment]
@raelgc Sure.

Interesting, how file system access is to be handled? The software is installed and run from system directories by a user that has no access to write `.pyc` files there.

**Comment by raelgc** [comment]
@giAtSDU Two options here:
1. I can just keep the `.py` files, as python is an interpreted language.
2. I can ask for the `.deb` package, during install, to compile all `.py` to `.pyc`.

I'll pick the second.

**Comment by raelgc** [comment]
@giAtSDU Changes uploaded!

Can you again, please, run a `sudo apt-get update && sudo apt-get upgrade`?

**Comment by giAtSDU** [comment]
Now it is working. Still need to test notifications

**Comment by raelgc** [comment]
@giAtSDU You can test notification in `Preferences` and click on `Send test notification`.

**Pull request merged**
