### PR TITLE
Fixed Width

### PR DESCRIPTION
**Pull request by raelgc**
Please add support for the Slack fixed width markup, via backticks:
https://slack.zendesk.com/hc/en-us/articles/202288908-Formatting-your-messages

### CODE REVIEW

**Comment by raelgc** [comment]
@someben Can you explain a bit more? I use the backticks all the time, as this is something internal to Slack.

How ScudCloud is performing this different then the web version?

**Comment by someben** [comment]
@raelgc Thanks for looking into this. Here is the Slack web client:
    https://dl.dropboxusercontent.com/u/46801122/slackweb.png

And here is the same under v1.0-20 of ScudCloud on Linux Mint 17.1:
    https://dl.dropboxusercontent.com/u/46801122/scudcloud.png

Note that the font is not actually fixed-width.

**Comment by raelgc** [comment]
@someben Thanks for clarify that!

I'll need to inspect that in browser to mark the same font as a required package. The reason I didn't see that is probably because I already have that font installed.

**Comment by raelgc** [comment]
@someben Can you, please, install this package? It contains one of the fonts used by Slack as fixed width (`Courier New`) and it's available in Ubuntu:

```
sudo apt-get install ttf-mscorefonts-installer
```

Then restart Scudcloud.

**Comment by someben** [comment]
Yup, that fixed it!

**Pull request merged**
