### PR TITLE
New instructions for Ubuntu 12.04 (#388)

### LINKED ISSUE #388: Unmet python3 dependency on ubuntu 12.04
Hello! I'm having an issue while trying to install on ubuntu 12.04

The error message I get is:

```
The following packages have unmet dependencies:
 scudcloud : Depends: python3 (>= 3.4) but 3.2.3-0ubuntu1.2 is installed.
             Depends: python3-dbus but it is not going to be installed.
             Depends: python3-dbus.mainloop.qt but it is not going to be installed.
             Depends: python3-notify2 but it is not going to be installed.
             Depends: python3-pyqt4 but it is not going to be installed.

```

Already tried installing python3.4 and it didn't help since the dependency is python3 >=3.4 but I have python3=3.2.3-0ubuntu1.2 and python3.4 instead.

Any help would be appreciated!

(I've already considered the libqtwebkit4 backport mentioned in the Readme)

### PR DESCRIPTION
**Pull request by raelgc**
Fixes #388

### CODE REVIEW

**Comment by immerrr** [comment]
You can take `dh-python` from my backports repository: https://launchpad.net/~immerrr-k/+archive/ubuntu/mmr-backports. It has no other build-deps, so you can just add it to the precise PPA.

**Comment by raelgc** [comment]
Nice, @immerrr!

Just got wondering if Launchpad will work when the build dependency is not present in the system (but available as a package in the same repo). Of course, testing this will give the answer!

**Comment by immerrr** [comment]
It works perfectly fine :)

**Comment by raelgc** [comment]
I've copied the `dh-python` package from your repo, and tried build again, but still the same error: https://launchpadlibrarian.net/238253108/buildlog_ubuntu-precise-i386.scudcloud_1.14-1_BUILDING.txt.gz

**Comment by immerrr** [comment]
Did you add `dh-python` as Build-Dep?

**Comment by raelgc** [comment]
No, let me try. 

By the way, send me your email to rael.gc@gmail.com, so I can add you in the Slack team, so we can discuss these details in an easy/fast way :)

**Pull request merged**
