### PR TITLE
Workaround for icon if theme name is empty (#524)

### PR DESCRIPTION
**Pull request by ben-cohen**
PR for #524 "Missing tray icon when minimised".

### CODE REVIEW

**Comment by raelgc** [comment]
Thank you @ben-cohen!

Just to double check: you tested in: KDE, Unity and in any of the problematic DEs?

**Comment by ben-cohen** [comment]
I tested on Linux Mint 17 Cinnamon.  I haven't tested on anything else.

**Comment by ben-cohen** [comment]
... where Cinnamon is one of the problematic DEs!

**Comment by raelgc** [comment]
Ok. I'll test on Unity.

**Comment by ben-cohen** [comment]
Thanks :)

**Comment by raelgc** [comment]
Worked fine in Unity.

**Pull request merged**
