### PR TITLE
crash on ubuntu 14.04

### PR DESCRIPTION
**Pull request by raelgc**
Hi,

I am trying to install scudcloud on Ubuntu 14.04 LTS freshly installed, but it does not start, please see the error below.

anything I can do to help ? Looking forward to have a linux slack app :)

Cheers,

```
Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 2135, in _find_spec
AttributeError: 'DynamicImporter' object has no attribute 'find_spec'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/scudcloud", line 6, in <module>
    from scudcloud import ScudCloud
  File "/opt/scudcloud/lib/scudcloud.py", line 10, in <module>
    from gi.repository import Unity, GObject, Dbusmenu
  File "/usr/lib/python3/dist-packages/gi/importer.py", line 53, in find_module
    'introspection typelib not found' % namespace)
ImportError: cannot import name Unity, introspection typelib not found
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 138, in apport_excepthook
    os.O_WRONLY | os.O_CREAT | os.O_EXCL, 0o640), 'wb') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/var/crash/_opt_scudcloud_scudcloud.10104.crash'

Original exception was:
Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 2135, in _find_spec
AttributeError: 'DynamicImporter' object has no attribute 'find_spec'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/scudcloud", line 6, in <module>
    from scudcloud import ScudCloud
  File "/opt/scudcloud/lib/scudcloud.py", line 10, in <module>
    from gi.repository import Unity, GObject, Dbusmenu
  File "/usr/lib/python3/dist-packages/gi/importer.py", line 53, in find_module
    'introspection typelib not found' % namespace)
ImportError: cannot import name Unity, introspection typelib not found
```

### CODE REVIEW

**Comment by raelgc** [comment]
Hi @OlivierBondu, thanks for reporting this issue!

This sounds like a missing dependency from my side.

Can you try install the `gir1.2-unity-5.0` package?

```
sudo apt-get install gir1.2-unity-5.0
```

And then try run ScudCloud again?

**Comment by raelgc** [comment]
Please, let me know if that works :)

**Comment by OlivierBondu** [comment]
It does :) thanks !

**Comment by immerrr** [comment]
In the same vein you might want to add `gir1.2-dbusmenu-glib-0.4`

```
$ python3
Python 3.2.3 (default, Feb 27 2014, 21:31:18) 
[GCC 4.6.3] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from gi.repository import Dbusmenu
>>> Dbusmenu
<gi.module.DynamicModule 'Dbusmenu' from b'/usr/lib/girepository-1.0/Dbusmenu-0.4.typelib'>
>>> 
$ dpkg -S Dbusmenu-0.4.typelib
gir1.2-dbusmenu-glib-0.4: /usr/lib/girepository-1.0/Dbusmenu-0.4.typelib
```

`gi.repository.GObject` import is unused atm, but if you want to keep it, you'll also need `gir1.2-glib-2.0`.

**Comment by raelgc** [comment]
@immerrr I remember to force the import of `GObject` due a weird problem of `Gi` complaining about 2 incompatibility versions of `GObject` (so, when I import it first from `Gi`, this warning disappears). But I should test again.

About `gir1.2-glib-2.0`, it's a requirement for `gir1.2-unity-5.0`: http://packages.ubuntu.com/trusty/gir1.2-unity-5.0

**Pull request merged**
