### PR TITLE
add contributing.md

### PR DESCRIPTION
**Pull request by jshawl**
I'd like to add how to inspect the application inside the Qt wrapper. Currently running `$ scudcloud --debug=True` and `$ scudcloud --debug` do not produce output in the console.

Is it possible to inspect element or `console.log` while the application is running?

### CODE REVIEW

**Comment by raelgc** [comment]
Thank you @jshawl!

And, `scudcloud --debug=True` is only to turn on the webkit console, to help to debug HTML/CSS/JS issues. As it's requires a lot of resources, the console is not enabled by default.

**Comment by jshawl** [comment]
Thanks rael! How can I enable the console?

On Thursday, April 30, 2015, Rael Gugelmin Cunha notifications@github.com
wrote:

> Thank you @jshawl https://github.com/jshawl!
> 
> And, scudcloud --debug=True is only to turn on the webkit console, to
> help to debug HTML/CSS/JS issues. As it's requires a lot of resources, the
> console is not enabled by default.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/raelgc/scudcloud/pull/84#issuecomment-97891262.

## 

Jesse Shawl
http://jshawl.com

**Comment by raelgc** [comment]
Run `scudcloud --debug=True` and then right click in any place in ScudCloud. You'll see the `Inspect Element` option.

**Comment by jshawl** [comment]
Awesome! Thank you!! pr for #81 coming soon

**Comment by raelgc** [comment]
@jshawl In case you need take a look in the scudcloud.js file, but without optimization/obfuscation, take a look here: https://gist.github.com/raelgc/9be7b48f4793c65232c2

**Comment by michaelherold** [comment]
@raelgc It would be handy to have the unoptimized version in the repository. That we we could minify it in the build process. Is there a reason you want to keep it out?

**Pull request merged**
