### PR TITLE
Blank white screen

### PR DESCRIPTION
**Pull request by raelgc**
Hello! I'm excited to check out this project, but it looks like the PPA package is having some issues for me. When I run it, I just get an empty blank white window with the title "ScudCloud." I've tested other Qt webkit software like the arora browser, and that works just great. So I'm not sure where to go from here to debug this further.

### CODE REVIEW

**Comment by raelgc** [comment]
Hi @martinb3, thanks for the bug reporting!

Can you tell me which Ubuntu version are you using?

And, additionally, can you open the program from the terminal to tell me which output is producing?

**Comment by raelgc** [comment]
@martinb3 Just to double check: did you notice the dialog asking for your Slack subdomain/identifier, right?

Because this is the behavior: in your first login, you'll face a blank screen with a dialog, which will ask your Slack subdomain/identifier.

**Comment by martinb3** [comment]
Hi! Yes, I did fill out the slack identifier. I assume that means the domain (I filled it in with the domain, based on reviewing the source and assuming that's what it was). No where on the Slack site does it call it an identifier, so you may want to clarify that :).

I verified the identifier gets saved in `~/.scudcloud` as well.

I'm on Ubuntu 14.10; there's no terminal output when run through the terminal. When I do an `strace`, there's tons of info every time the mouse cursor runs over the empty white window, so I couldn't grep down too much there either.

Thanks!

**Comment by raelgc** [comment]
@martinb3 The identifier should be only the `subdomain` before the `.slack.com` part, and you're right when I need to clarify that.

By example: my Slack domain for test is `raelcunha.slack.com`, so my identifier is `raelcunha`.

Can you tell me if using this way it works? If not, I'll download a copy of 14.10 to debug.

**Comment by raelgc** [comment]
@martinb3 I've edited the `README` file to include this info. Thank you for pointing me about the lack of explanation about the Identifier.

Are you now able to properly run the program?

**Comment by raelgc** [comment]
@martinb3 After you complain, I've tried to improve the first signin, and found the Slack pure login page (without the sub-domain). So I've improved the first signin to use that page.

**Comment by martinb3** [comment]
Thanks, that fixed it for me! I still see a "something went wrong" after I login on the slack webpage, but then the UI loads and everything works fine.

**Pull request merged**
