### PR TITLE
Add option to change dictionary for Hunspell

### PR DESCRIPTION
**Pull request by jcul**
On my system, my language is set to en_IE.

This is the dictionary that hunspell looks for, but there isn't a hunspell package for en_IE.

Added an option to scudcloud.cfg so you can overwrite this.
e.g.
Hunspell=en_GB

### CODE REVIEW

**Comment by raelgc** [comment]
Hi @jcul and thanks for the PR.

The `libqtwebkit-qupzillaplugins` package is required to display the red underlines in misspelled words.

**Comment by jcul** [comment]
Hey, I can revert that last commit.

One issue I have with libqtwebkit-qupzillaplugins is I get this misleading error:

```
SpellCheck: Cannot find dictionaries for "/usr/share/hunspell/en_IE" 
SpellCheck: Initialization failed! 
```

Even though it's now using scudcloud/speller.py with the correct dictionary and not the one from libqtwebkit-qupzillaplugins.

Also, I don't get the red underlines, even with libqtwebkit-qupzillaplugins installed, so maybe it's doing the spell check independently of scudcloud/speller.py ?

**Comment by raelgc** [comment]
@jcul Yes, this library will check independently from ScudCloud. It's a C code required for webkit. You can see at https://github.com/raelgc/libqtwebkit-qupzillaplugins. If you can change it to read from our config file, then we can fix both.

**Comment by jcul** [comment]
So libqtwebkit-qupzillaplugins checks DICTONARY / DICPATH environment variable before checking the locale, so I suppose it would be easy to just set those variables also.

On second thought though, maybe it's easier to just use hunspell symlinks for this.
Was just going to try it on my laptop (arch linux) and I found this is the way hunspell is already set up on Arch anyway. It was ubuntu where I had the issue earlier.

```
lrwxrwxrwx   1 root root     15 Aug 21 09:45 en_IE.aff -> en_GB-large.aff
lrwxrwxrwx   1 root root     15 Aug 21 09:45 en_IE.dic -> en_GB-large.dic
```

**Pull request closed without merging**
